### ISSUE TITLE
cannot compile 15.0.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by suprnurd** [BTCGPU/BTCGPU#171]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please see the official [Bitcoin Gold website](https://btcgpu.org/).

The core will not compile on Ubuntu 16.04 in a production environment that is currently running many other core wallets.

Error message:
./crypto/common.h:16:20: fatal error: sodium.h: No such file or directory

#### If so, please list the steps to reproduce below:
1. clone the repo, checkout the 15.0.1 tag
2. ./autogen.sh
3. ./configure --without-gui --disable-tests
4. make

### Expected behaviour
The core should compile.

### Actual behaviour
The compile does not complete, dies almost immediately.

### What version of bitcoin-core are you using?
commit 287d089679e7ca48acd3d49d57d3697c3030b74e
tag 0.15.0.1

### Machine specs:
- OS: Ubuntu 16.04 x64 4.4.0-98-generic
- CPU: Intel Core i3
- RAM: 8GB
- Disk size: 2TB
- Disk Type (HD/SDD): SSHD

### Any extra information that might be useful in the debugging process.

Making all in src
make[1]: Entering directory '/var/repo/bitcoingold/src'
make[2]: Entering directory '/var/repo/bitcoingold/src'
  CXX      bgoldd-bitcoind.o
In file included from ./uint256.h:15:0,
                 from consensus/params.h:9,
                 from chainparams.h:10,
                 from bitcoind.cpp:10:
./crypto/common.h:16:20: fatal error: sodium.h: No such file or directory
compilation terminated.
Makefile:8093: recipe for target 'bgoldd-bitcoind.o' failed
make[2]: *** [bgoldd-bitcoind.o] Error 1
make[2]: Leaving directory '/var/repo/bitcoingold/src'
Makefile:9351: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/repo/bitcoingold/src'
Makefile:741: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by unclemusclez** [comment]
from https://github.com/BTCGPU/BTCGPU/issues/43

Workaround for Ubuntu 16.04 Xenial Users (may not work for you.)

Download deb files from https://packages.ubuntu.com/artful/libsodium-dev and https://packages.ubuntu.com/artful/libsodium18 for your architecture, e.g.

wget http://de.archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium-dev_1.0.13-1_amd64.deb
wget http://de.archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium18_1.0.13-1_amd64.deb
This gives you libsodium 1.0.13 from Ubuntu 17.10 (Artful) which can be installed on 16.04 without problems since it only has a dependency on libc6:

dpkg -i libsodium*deb
Now compile BTCGPU. No assertion anymore when starting bgoldd.

or, if that doesnt work:

Solution

Step 1) Install Dependencies:

sudo apt install libsodium18

Manually compile / install libsodium-dev v1.0.13 or later from https://download.libsodium.org/libsodium/releases/ (Make sure no older versions are installed)

./configure && make && make test && sudo make install

./sudo ldconfig

Step 2) Compile daemon and Qt

cd BTCGPU && ./autogen.sh && ./configure && make
Step 3) Run / test daemon

./bgoldd
In separate terminal:

./bgold-cli getblockchaininfo

**Comment by unclemusclez** [comment]
make sure to also `cd depends` and `make` before running `make` in the parent directory

**Comment by suprnurd** [comment]
The first method referenced above (downloading the .deb packages and manually installing them) worked fine for me I was able to both compile the core and also start the daemon.

Thank you very much!

**Comment by skoroneos** [comment]
An additional way is to install it from a ppa

sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update
sudo apt-get install -y libsodium-dev
