### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by georgk10** [BTCGPU/BTCGPU#40]
### Describe the issue
Followed the build instructions 1:1 on ubuntu 16.04 64bit. ran autogen and afterwards config, then this error occured:
configure error: Could not link against boost_system
solution:
instead of ./configure , use: 
./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu

### Can you reliably reproduce the issue?
1.Followed the build instructions on ubuntu 16.04 64 bit
2.ran ./autogen.sh
3.ran ./configure

### Expected behaviour
build bitcoin gold

### Actual behaviour
error message

Just wanted to clear things up in case someone else got the same problem :)

**Comment by D3m0nKingx** [comment]
do you have boost installed? 

`sudo apt install libboost1.58-all-dev`

**Comment by sinclar2009** [comment]
try to build on osx 10.13 have error:
Johns-MacBook:BTCGPU johngalata$ make
Making all in src
  CXX      crypto/libbitcoinconsensus_la-aes.lo
In file included from crypto/aes.cpp:6:
./crypto/common.h:16:10: fatal error: 'sodium.h' file not found
#include "sodium.h"
         ^~~~~~~~~~
1 error generated.
make[2]: *** [crypto/libbitcoinconsensus_la-aes.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1


how to resolve?

**Comment by jagottsicher** [comment]
missing libsodium?
I fixed the problem on 14.04 with
removig existing version

downloading 1.0.15 from https://download.libsodium.org/libsodium/releases/libsodium-1.0.15.tar.gz

untar and cd into the dir

then ye good olde:
./configure make && make check sudo make install
and finally:
ldconfig
done.

If you are not root put "sudo" in front of the commands

afterwards recompile BTCGPU.

#43 #53 #46

**Comment by sinclar2009** [comment]
now I have error 
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libbitcoinconsensus.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by DLee-AU** [comment]
I just spun up a vagrant ubuntu 17.10 a few days ago and then just went through the build unix doco.

For sodium i just utilised 
sudo apt-get install libsodium-dev

Manually compiled and installed Db 4.8 as per the doco

Worked like a charm ....

**Comment by c0deright** [comment]
Please see https://github.com/BTCGPU/BTCGPU/issues/43#issuecomment-338683228

**Comment by StarbuckBG** [comment]
#43 solves it. If not please post comment and reopen the ticket.
